<a href="https://colab.research.google.com/github/AffanHashmi4/AffanHashmi4-SSUET-DataScience/blob/main/AI%20Class%2014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int64')

In [5]:
arr = arr.astype('int8')

In [6]:
arr.dtype

dtype('int8')

In [7]:
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [14]:
arr = arr * arr

In [15]:
arr

array([ 1,  4,  9, 16, 25])

In [16]:
arr

array([ 1,  4,  9, 16, 25])

In [17]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2 = np.arange(20).reshape(4, 5)

In [21]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
arr3 = np.arange(45).reshape(3, 3, 5)

In [23]:
arr3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])